### ISSUE TITLE
Passing Parameter to HTTP Adapter  return nothing

### ISSUE THREAD

**Issue by zahidaziz** [MobileFirst-Platform-Developer-Center/AdapterMashup#1]
Hi, Im using HTTP adapter to make request to third party application. How the exact way to pass parameters to the adapter from client? I used postman, CLI but the adapter still return nothing. Please help? thanks

**Comment by NathanHazout** [comment]
Is this related to the Adapter Mashup sample??
This place is only for issues regarding the AdapterMashup sample.

If it's a general question, please try StackOverflow.

**Comment by zahidaziz** [comment]
I didnt found "HTTP Adapter" repo to shoot the issue... What do you mean It's a general question?? I have been searching for the answer in past 3 days.. Come on

**Comment by NathanHazout** [comment]
What I mean by general is, it's not really a question about this sample. Usually GitHub issues are when you download this specific sample, and something does not work as expected.

For JavaScript HTTP adapters, you could get started with this tutorial (it also includes a sample): 
https://developer.ibm.com/mobilefirstplatform/documentation/getting-started-7-1/foundation/server-side-development-category/javascript-adapters/js-http-adapter/

For general adapters information, including how to test them there is: https://developer.ibm.com/mobilefirstplatform/documentation/getting-started-7-1/foundation/server-side-development-category/adapter-framework-overview/

If it does not help, I recommend asking on StackOverflow (give code snippets and details), we'll help you there.
